version: "3"
networks:
  example:
    driver: bridge

services:
  smarterproxy:
    container_name: smarterproxy
    image: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      # - ./docker/proxy/service-example/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/_.evl.uic.edu.key:/etc/ssl/evl.key
      - ./cert/_.evl.uic.edu.crt:/etc/ssl/evl.crt
      - ./proxy/https-forwarding.conf:/etc/nginx/conf.d/https-forwarding.conf
    networks:
      - example
  smarterfrontend:
    container_name: smarterfrontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app/smarter
    networks:
      - example
  smarterbackend:
    container_name: smarterbackend
    restart: unless-stopped
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/app/smarter
    networks:
      - example
